### ISSUE TITLE
Step ReceiptGenerator/draw_receipt Fail

### ISSUE THREAD

**Issue by sgatrip** [billstark/receipt-scanner#8]
On "python draw_receipt.py 10"
we got sometime an error.

before to execute i changes draw_receipt.py line 414 to use function create_sample

```
        else:
            #create_noised_crnn_sample(count) # todo ael : default ?
            create_sample(count)
```

Program generate some receipt, but sometime we got an error

```
Traceback (most recent call last):
  File "draw_receipt.py", line 415, in <module>
    create_sample(count)
  File "draw_receipt.py", line 397, in create_sample
    draw_receipt_with_letter_boxes(debug=True)
  File "draw_receipt.py", line 225, in draw_receipt_with_letter_boxes
    text = items_text + item_space + separator_line + item_space + item_to_text(item_list['total'], num_col, dist_name_price, break_long_words)
  File "draw_receipt.py", line 50, in item_to_text
    lines = wrapper.wrap(name)
  File "C:\Users\ael\Anaconda3\lib\textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "C:\Users\ael\Anaconda3\lib\textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -2 (must be > 0)
```

is this normal ?  or i missing some configuration ?

Regards

**Comment by billstark** [comment]
@DesperadoFlames Could you please have a look at it? Thanks!

**Comment by sgatrip** [comment]
no news from long time.
is this project will be maintain or not ?

**Comment by billstark** [comment]
@sgatrip Sorry I suppose for now the project is not under maintenance. I will let you know when we are working on it again! Sorry about it!
